### ISSUE TITLE
the carla version?

### ISSUE THREAD

**Issue by meteorshowers** [enginBozkurt/carla-training-data#1]
could you please tell me the carla version?
@enginBozkurt

**Comment by enginBozkurt** [comment]
It is 0.8.3 version

**Comment by Rajat-Mehta** [comment]
Can we use it with the latest Carla 0.9.8 version? Do i need to change anything for that?

**Comment by enginBozkurt** [comment]
After Carla 0.9.1 version,all  the framework API is changed. So you could
not use it.
But if you apply and convert similar concepts for the new API , you could
apply it for the newer version.

**Comment by MathieuSeraphim** [comment]
Hello,

I tried to run the program with Carla 8.3, but I get the following error message:
```
ERROR: (localhost:2000) failed to connect: [Errno 111] Connection refused
```
Do you know where it might come from?
